spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://*******:****/comment?useUnicode=true&characterEncoding=utf8
    username: ****
    password: *****
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  data:
    mongodb:
      uri: *****************************
      connections-per-host: 100
server:
  context-path: /subscribe
  port: 8080

authorizeUrl:
  domainName: http://www.linge.wang
  path: /demo/wechat/authorize
  subscribe: http://linge.natapp1.cc
