
spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///subscribe?characterEncoding=utf-8&useSSL=false

  data:
    mongodb:
      uri: mongodb://user1:123456@120.77.241.246:27017/test
      connections-per-host: 100

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  context-path: /subscribe
  port: 8080

authorizeUrl:
  domainName: http://www.linge.wang
  path: /demo/wechat/authorize
  subscribe: http://linge.natapp1.cc